// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    About: typeof import('./components/sections/About.vue')['default']
    Footer: typeof import('./components/snippets/Footer.vue')['default']
    Header: typeof import('./components/snippets/Header.vue')['default']
    Hero: typeof import('./components/sections/Hero.vue')['default']
    HeroPattern: typeof import('./components/snippets/HeroPattern.vue')['default']
    Logos: typeof import('./components/sections/Logos.vue')['default']
    Marquee: typeof import('./components/snippets/Marquee.vue')['default']
    Marquees: typeof import('./components/sections/Marquees.vue')['default']
    ProjectCard: typeof import('./components/snippets/ProjectCard.vue')['default']
    Projects: typeof import('./components/sections/Projects.vue')['default']
    README: typeof import('./components/README.md')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TypewriterText: typeof import('./components/snippets/TypewriterText.vue')['default']
    VerticalScrollingText: typeof import('./components/snippets/VerticalScrollingText.vue')['default']
  }
}

export {}
